package uranium.nz.bot.ui;

public enum UIStates {
    ROOT, ADD_USER, REMOVE_USER, FIND_USER, CHANGE_USER, AWAITING_ADD_TYPE, AWAITING_MAIN_USERNAME, AWAITING_TWIN_USERNAME, AWAITING_REMOVE_TYPE, SHOWING_FIND_RESULT, AWAITING_MAIN_REMOVE_CONFIRMATION, AWAITING_TWIN_REMOVE_CONFIRMATION
}
